export const top_snacks = [
  {
    id: "mostpopularproducts",
    name: "Most Popular",
    items: [
      {
        id: "dabaowangzhongwang600g",
        name: "大包王中王",
        description: "600g 一包10根",
        ranking: 2,
        imgUrl: "",
        price: 10.5,
        price_unit: "包",
      },
      {
        id: "liuliangan30g",
        name: "榴莲干",
        description: "30g",
        ranking: 1,
        imgUrl: "",
        price: 4.5,
        price_unit: 0,
      },
      {
        id: "xianglazhuroufu168g",
        name: "香辣猪肉脯",
        description: "168g",
        ranking: 3,
        imgUrl: "",
        price: 5.5,
        price_unit: 0,
      },
      {
        id: "xiangbalaolujidan30g",
        name: "乡巴佬卤鸡蛋 (原味/蜜汁)",
        description: "30g",
        ranking: 999,
        imgUrl:
          "https://cdn.discordapp.com/attachments/1012617230053298256/1149866672740642826/IMG_2064.png",
        price: 7.5,
        price_unit: 0,
      },
    ],
  },
  {
    id: "mostdiscountproducts",
    name: "Most Discount",
    items: [
      {
        id: "dabaowangzhongwang600g",
        name: "大包王中王",
        description: "600g 一包10根",
        ranking: 999,
        imgUrl: "",
        price: 10.5,
        price_unit: "包",
      },
      {
        id: "zhongbaowangzhongwang400g",
        name: "中包王中王",
        description: "400g 一包10根",
        ranking: 999,
        imgUrl: "",
        price: 6.5,
        price_unit: "包",
      },
      {
        id: "xiaobaowangzhongwang240g",
        name: "小包王中王",
        description: "240g 一包8根",
        ranking: 999,
        imgUrl: "",
        price: 4.5,
        price_unit: 0,
      },
    ],
  },
];
export const snacks_all_category = [
  {
    id: "shuanghuixilie",
    name: "双汇系列",
    special: "买六送一",
    items: [
      {
        id: "dabaowangzhongwang600g",
        name: "大包王中王",
        description: "600g 一包10根",
        ranking: 999,
        imgUrl: "",
        price: 10.5,
        price_unit: "包",
      },
      {
        id: "zhongbaowangzhongwang400g",
        name: "中包王中王",
        description: "400g 一包10根",
        ranking: 999,
        imgUrl: "",
        price: 6.5,
        price_unit: "包",
      },
      {
        id: "xiaobaowangzhongwang240g",
        name: "小包王中王",
        description: "240g 一包8根",
        ranking: 999,
        imgUrl: "",
        price: 4.5,
        price_unit: 0,
      },
      {
        id: "xiangtianwangyumichang240g",
        name: "香甜王玉米肠",
        description: "240g 一包8根",
        ranking: 999,
        imgUrl: "",
        price: 4.5,
        price_unit: 0,
      },
    ],
  },
  {
    id: "youyouxilie",
    name: "有友系列",
    items: [
      {
        id: "dabaopaojiaofengzhao168g",
        name: "大包泡椒凤爪 (山椒)",
        description: "168g",
        ranking: 999,
        imgUrl: "",
        price: 4.5,
        price_unit: 0,
      },
      {
        id: "zhongbaopaojiaofengzhao95g",
        name: "中包泡椒凤爪 (山椒)",
        description: "95g",
        ranking: 999,
        imgUrl: "",
        price: 3.5,
        price_unit: 0,
      },
      {
        id: "xiaobaopaojiaofengzhao70g",
        name: "小包泡椒凤爪 (山椒)",
        description: "70g",
        ranking: 999,
        imgUrl: "",
        price: 2.5,
        price_unit: 0,
      },
      {
        id: "pajiaozhusun80g",
        name: "泡椒竹笋",
        description: "80g",
        ranking: 999,
        imgUrl: "",
        price: 3.0,
        price_unit: 0,
      },
    ],
  },
  {
    id: "sanzhisongshuxilie",
    name: "三只松鼠系列",
    items: [
      {
        id: "liuliangan30g",
        name: "榴莲干",
        description: "30g",
        ranking: 999,
        imgUrl: "",
        price: 4.5,
        price_unit: 0,
      },
      {
        id: "mangguogan60g",
        name: "芒果干",
        description: "60g",
        ranking: 999,
        imgUrl: "",
        price: 4.5,
        price_unit: 0,
      },
      {
        id: "caomeigan60g",
        name: "草莓干",
        description: "60g",
        ranking: 999,
        imgUrl: "",
        price: 4.5,
        price_unit: 0,
      },
      {
        id: "huangtaogan60g",
        name: "黄桃干",
        description: "60g",
        ranking: 999,
        imgUrl: "",
        price: 4.5,
        price_unit: 0,
      },
      {
        id: "shuxiangniurou100g",
        name: "蜀香牛肉",
        description: "100g",
        ranking: 999,
        imgUrl: "",
        price: 6.5,
        price_unit: 0,
      },
      {
        id: "heiyaweicuioupian150g",
        name: "黑鸭味脆藕片",
        description: "150g",
        ranking: 999,
        imgUrl: "",
        price: 5.5,
        price_unit: 0,
      },
      {
        id: "qugufengzhao110g",
        name: "去骨凤爪 (柠檬酸辣味)",
        description: "110g ",
        ranking: 999,
        imgUrl: "",
        price: 8.5,
        price_unit: 0,
      },
    ],
  },
  {
    id: "wangxiaoluxilie",
    name: "王小卤系列",
    items: [
      {
        id: "xiandanhuangyupi35g",
        name: "咸蛋黄鱼皮",
        description: "35g",
        ranking: 999,
        imgUrl: "",
        price: 4.5,
        price_unit: 0,
      },
      {
        id: "luxianghupifengzhao210g",
        name: "卤香虎皮凤爪",
        description: "210g 一包五个",
        ranking: 999,
        imgUrl: "",
        price: 8.5,
        price_unit: 0,
      },
    ],
  },
  {
    id: "feijiuzhuroufuxilie",
    name: "肥揪猪肉脯系列",
    items: [
      {
        id: "ziranzhuroufu168g",
        name: "孜然猪肉脯",
        description: "168g",
        ranking: 999,
        imgUrl: "",
        price: 5.5,
        price_unit: 0,
      },
      {
        id: "xianglazhuroufu168g",
        name: "香辣猪肉脯",
        description: "168g",
        ranking: 999,
        imgUrl: "",
        price: 5.5,
        price_unit: 0,
      },
      {
        id: "mizhizhuroufu168g",
        name: "蜜汁猪肉脯",
        description: "168g",
        ranking: 999,
        imgUrl: "",
        price: 5.5,
        price_unit: 0,
      },
      {
        id: "yuanweizhuroufu168g",
        name: "原味猪肉脯",
        description: "168g",
        ranking: 999,
        imgUrl: "",
        price: 5.5,
        price_unit: 0,
      },
    ],
  },
  {
    id: "luxiangxilie",
    name: "卤香系列",
    items: [
      {
        id: "xiangbalaoxiaojitui75g",
        name: "乡巴佬小鸡腿",
        description: "75g 一包10个",
        ranking: 999,
        imgUrl:
          "https://cdn.discordapp.com/attachments/1012617230053298256/1149866687634604182/IMG_2063.png",
        price: 12,
        price_unit: 0,
      },
      {
        id: "xiangbalaolujidan30g",
        name: "乡巴佬卤鸡蛋 (原味/蜜汁)",
        description: "30g",
        ranking: 999,
        imgUrl:
          "https://cdn.discordapp.com/attachments/1012617230053298256/1149866672740642826/IMG_2064.png",
        price: 7.5,
        price_unit: 0,
      },
      {
        id: "xiangbalaoluanchundan30g",
        name: "乡巴佬卤鹌鹑蛋",
        description: "30g 一包四粒",
        ranking: 999,
        imgUrl: "",
        price: 2.5,
        price_unit: 0,
      },
    ],
  },
  {
    id: "jiapinxilie",
    name: "佳品系列",
    items: [
      {
        id: "tanshaokaochang145g",
        name: "炭烧烤肠",
        description: "145g",
        ranking: 999,
        imgUrl: "",
        price: 8.5,
        price_unit: 0,
      },
      {
        id: "ailajizhua50g",
        name: "爱辣鸡爪",
        description: "50g 一包4根",
        ranking: 999,
        imgUrl:
          "https://cdn.discordapp.com/attachments/1012617230053298256/1149866572400300223/IMG_2066.png",
        price: 3.5,
        price_unit: 0,
      },
      {
        id: "tianyijiaoniurougan30",
        name: "天一角牛肉干 (炭烤/爽辣)",
        description: "30g",
        ranking: 999,
        imgUrl: "",
        price: 1.5,
        price_unit: 0,
      },
      {
        id: "xianggufeiniuzhenxiangpaidabao80g",
        name: "香菇肥牛祯香牌大包",
        description: "80g",
        ranking: 999,
        imgUrl:
          "https://cdn.discordapp.com/attachments/1012617230053298256/1149866557086904391/IMG_2067.png",
        price: 2.5,
        price_unit: 0,
      },
      {
        id: "pinggeyazhua26g",
        name: "平哥鸭爪 (香辣/鲜香)",
        description: "26g",
        ranking: 999,
        imgUrl: "",
        price: 1.5,
        price_unit: 0,
      },
    ],
  },
  {
    id: "shanghaojiaxilie",
    name: "上好佳系列",
    items: [
      {
        id: "tianyuanshupian50g",
        name: "田园薯片 (番茄/甜辣/烤肉)",
        description: "50g",
        ranking: 999,
        imgUrl:
          "https://cdn.discordapp.com/attachments/1012617230053298256/1149866546886352988/IMG_2068.png",
        price: 2.5,
        price_unit: 0,
      },
      {
        id: "xianxiapian40g",
        name: "鲜虾片",
        description: "40g",
        ranking: 999,
        imgUrl:
          "https://cdn.discordapp.com/attachments/1012617230053298256/1149866546886352988/IMG_2068.png",
        price: 2,
        price_unit: 0,
      },
      {
        id: "xiaohuanxionggancuimian35g",
        name: "小浣熊干脆面 (番茄/烤肉)",
        description: "35g",
        ranking: 999,
        imgUrl:
          "https://cdn.discordapp.com/attachments/1012617230053298256/1149866546886352988/IMG_2068.png",
        price: 1,
        price_unit: 0,
      },
      {
        id: "wangzaixiaomantoudabaozhuang192g",
        name: "旺仔小馒头大包装",
        description: "192g",
        ranking: 999,
        imgUrl:
          "https://cdn.discordapp.com/attachments/1012617230053298256/1149866538732630026/IMG_2069.png",
        price: 4.5,
        price_unit: 0,
      },
    ],
  },
  {
    id: "xizhilangxilie",
    name: "喜之郎系列",
    items: [
      {
        id: "rusuanjunguodong120g",
        name: "乳酸菌果冻",
        description: "120g 一袋6小包",
        description_line2: "口味: 葡萄, 水蜜桃, 草莓, 芒果, 柠檬红茶, 葡萄茉莉",
        ranking: 999,
        imgUrl:
          "https://cdn.discordapp.com/attachments/1012617230053298256/1149866530948005928/IMG_2070.png",
        price: 2.5,
        price_unit: 0,
      },
    ],
  },
  {
    id: "jueyixilie",
    name: "绝艺系列",
    items: [
      {
        id: "malahaidai176g",
        name: "麻辣海带",
        description: "176g",
        ranking: 999,
        imgUrl: "",
        price: 5.5,
        price_unit: 0,
      },
      {
        id: "xianglayabo540g",
        name: "香辣鸭脖 (微辣)",
        description: "540g",
        ranking: 999,
        imgUrl: "",
        price: 13.5,
        price_unit: 0,
      },
      {
        id: "laoyeyekaoyupiuan95g",
        name: "老爷爷烤鱼片 (原味/微辣)",
        description: "95g",
        ranking: 999,
        imgUrl: "",
        price: 10.5,
        price_unit: 0,
      },
    ],
  },
  {
    id: "tangdarenxilie",
    name: "汤达人系列",
    items: [
      {
        id: "yuanweitungulamian125g",
        name: "原味豚骨拉面",
        description: "125g 一袋五包",
        price: 10.5,
        ranking: 999,
        imgUrl:
          "https://cdn.discordapp.com/attachments/1012617230053298256/1149866522295148594/IMG_2072.png",
      },
      {
        id: "suanlatungulamian125g",
        name: "酸辣豚骨拉面",
        description: "125g 一袋五包",
        price: 10.5,
        ranking: 999,
        imgUrl:
          "https://cdn.discordapp.com/attachments/1012617230053298256/1149866522295148594/IMG_2072.png",
      },
    ],
  },
];
